var stageonedata = [
  {
    "tipequiz": 1,
    "gambar": "assets/Logo_Pahlawanku.png",
    "soal": "siapakah nama tokoh ini?",
    "jawabansatu": "Ir. Soekarno",
    "validsatu": false,
    "jawabandua": "Dr Soepomo",
    "validdua": false,
    "jawabantiga": "Pangeran Diponegoro",
    "validtiga": true,
    "jawabanempat": "Pattimura",
    "validempat": false,
  },
  {
    "tipequiz": 2,
    "soal": "siapakah nama tokoh ini?",
    "jawabansatu": "assets/Logo_Pahlawanku.png",
    "validsatu": false,
    "jawabandua": "assets/Logo_Pahlawanku.png",
    "validdua": false,
    "jawabantiga": "assets/Logo_Pahlawanku.png",
    "validtiga": true,
    "jawabanempat": "assets/Logo_Pahlawanku.png",
    "validempat": false,
  },
  {
    "tipequiz": 1,
    "gambar": "assets/Logo_Pahlawanku.png",
    "soal": "siapakah nama tokoh ini?",
    "jawabansatu": "Ir. Soekarno",
    "validsatu": false,
    "jawabandua": "Dr Soepomo",
    "validdua": false,
    "jawabantiga": "Pangeran Diponegoro",
    "validtiga": true,
    "jawabanempat": "Pattimura",
    "validempat": false,
  },
  {
    "tipequiz": 2,
    "soal": "siapakah nama tokoh ini?",
    "jawabansatu": "assets/Logo_Pahlawanku.png",
    "validsatu": false,
    "jawabandua": "assets/Logo_Pahlawanku.png",
    "validdua": false,
    "jawabantiga": "assets/Logo_Pahlawanku.png",
    "validtiga": true,
    "jawabanempat": "assets/Logo_Pahlawanku.png",
    "validempat": false,
  },
  {
    "tipequiz": 1,
    "gambar": "assets/Logo_Pahlawanku.png",
    "soal": "siapakah nama tokoh ini?",
    "jawabansatu": "Ir. Soekarno",
    "validsatu": false,
    "jawabandua": "Dr Soepomo",
    "validdua": false,
    "jawabantiga": "Pangeran Diponegoro",
    "validtiga": true,
    "jawabanempat": "Pattimura",
    "validempat": false,
  },
];
var stagetwodata = [
  {
    "tipequiz": 1,
    "gambar": "assets/Logo_Pahlawanku.png",
    "soal": "siapakah nama tokoh ini?",
    "jawabansatu": "Ir. Soekarno",
    "validsatu": false,
    "jawabandua": "Dr Soepomo",
    "validdua": false,
    "jawabantiga": "Pangeran Diponegoro",
    "validtiga": true,
    "jawabanempat": "Pattimura",
    "validempat": false,
  },
];
var stagethreedata = [
  {
    "tipequiz": 1,
    "gambar": "assets/Logo_Pahlawanku.png",
    "soal": "siapakah nama tokoh ini?",
    "jawabansatu": "Ir. Soekarno",
    "validsatu": false,
    "jawabandua": "Dr Soepomo",
    "validdua": false,
    "jawabantiga": "Pangeran Diponegoro",
    "validtiga": true,
    "jawabanempat": "Pattimura",
    "validempat": false,
  },
];
var stagefourdata = [
  {
    "tipequiz": 1,
    "gambar": "assets/Logo_Pahlawanku.png",
    "soal": "siapakah nama tokoh ini?",
    "jawabansatu": "Ir. Soekarno",
    "validsatu": false,
    "jawabandua": "Dr Soepomo",
    "validdua": false,
    "jawabantiga": "Pangeran Diponegoro",
    "validtiga": true,
    "jawabanempat": "Pattimura",
    "validempat": false,
  },
];
var stagefivedata = [
  {
    "tipequiz": 1,
    "gambar": "assets/Logo_Pahlawanku.png",
    "soal": "siapakah nama tokoh ini?",
    "jawabansatu": "Ir. Soekarno",
    "validsatu": false,
    "jawabandua": "Dr Soepomo",
    "validdua": false,
    "jawabantiga": "Pangeran Diponegoro",
    "validtiga": true,
    "jawabanempat": "Pattimura",
    "validempat": false,
  },
];
var stagesixdata = [
  {
    "tipequiz": 1,
    "gambar": "assets/Logo_Pahlawanku.png",
    "soal": "siapakah nama tokoh ini?",
    "jawabansatu": "Ir. Soekarno",
    "validsatu": false,
    "jawabandua": "Dr Soepomo",
    "validdua": false,
    "jawabantiga": "Pangeran Diponegoro",
    "validtiga": true,
    "jawabanempat": "Pattimura",
    "validempat": false,
  },
];
var stagesevendata = [
  {
    "tipequiz": 1,
    "gambar": "assets/Logo_Pahlawanku.png",
    "soal": "siapakah nama tokoh ini?",
    "jawabansatu": "Ir. Soekarno",
    "validsatu": false,
    "jawabandua": "Dr Soepomo",
    "validdua": false,
    "jawabantiga": "Pangeran Diponegoro",
    "validtiga": true,
    "jawabanempat": "Pattimura",
    "validempat": false,
  },
];
var stageeightdata = [
  {
    "tipequiz": 1,
    "gambar": "assets/Logo_Pahlawanku.png",
    "soal": "siapakah nama tokoh ini?",
    "jawabansatu": "Ir. Soekarno",
    "validsatu": false,
    "jawabandua": "Dr Soepomo",
    "validdua": false,
    "jawabantiga": "Pangeran Diponegoro",
    "validtiga": true,
    "jawabanempat": "Pattimura",
    "validempat": false,
  },
];
